### ISSUE TITLE
auto-scale down the old now instance

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#126]
I run out of instances really quickly with all these auto-deployments. We need to automatically scale down the previous instance as soon as we add the new aliases. I think we just need to somehow find out what the current alias is pointing to, then do the new alias, then `now scale $OLD_NOW_ID 0`. I'm not sure of the best way to find the `$OLD_NOW_ID` though 🤔 

Alternatively, we could figure out how to build everything to a static site and do a static deployment. That would probably be pretty neat but take a little more work...

**Comment by sergiodxa** [comment]
Creating a static site it's not that hard, as far as I saw the pages are static right now, the only requirement is to define `exportPathMap` in the `next.config.js` with every possible route or dynamically generate them (not sure how). There is a PR with an example in the repo of Next.js -> https://github.com/zeit/next.js/pull/2234

In travis then you will need to build, export and deploy the exported directory full of HTML files. I can try configuring the `next.config.js` to export the pages.

**Comment by sergiodxa** [comment]
The way localization works right now made impossible to export the page because it's using the `req.headers.host`, and that doesn't exists when exporting 😞 that should be changed before being able to export the glamorous website.

About the instances, have you implemented `now-pipeline`? If so you can use `now-pipeline-prune` after aliasing to remove all non-aliased deployments. If you haven't implemented `now-pipeline` you can scale the alias with `now scale <alias> 1 auto` and then when you alias a new deployment it should reduce the amount of instances for the old one automatically 🤔

**Comment by sholladay** [comment]
> I run out of instances really quickly with all these auto-deployments.

Hmm as long as the scaling is set up properly, that shouldn't really happen since the old deploys should become frozen pretty quickly and anything that is frozen does not count towards the instance limit.

> I think we just need to somehow find out what the current alias is pointing to

`now ls my-alias` will do that for you. 😃

> do the new alias, then now scale $OLD_NOW_ID 0

Agreed. Or even `now remove $OLD_NOW_ID --yes`.

There is a _still cooler_ thing, `now remove my-app --safe` that is supposed to remove any deploys that do not have aliases. Seems it [is broken](https://github.com/zeit/now-cli/issues/670) at the moment, though.

**Comment by kentcdodds** [comment]
Ah, I hadn't done the `auto` bit. When I'm at a keyboard I'll try that. Would be an easy fix!

**Comment by kentcdodds** [comment]
Too bad:

```
$ now scale rc.glamorous.rocks 1 auto
> Error! Autoscaling requires pro or max plan
```

I think that the best thing we could do is figure out how to make this give us a static export and build it for every locale. Any tips?

**Comment by sholladay** [comment]
That message is misleading. You can autoscale between 0 and 1 on any plan.

**Comment by kentcdodds** [comment]
Hmmm... That's not what I think I was experiencing, but we'll see if we have more issues in the future. Thanks!

**Comment by kentcdodds** [comment]
Woo! We're now using static deploys with Next.js v3's export feature and it's amazing!

We don't need to worry about this anymore :tada:
