### ISSUE TITLE
Steps to Release

### ISSUE THREAD

**Issue by paulmolluzzo** [kentcdodds/glamorous-website#204]
**Problem Description:**

It's unclear what we need to finish before we release.

**Suggested Solution:**

If we're not going to use the Projects tab (I'm not keen on it personally), let's list the remaining items in a single issue or mark the issues that are required assign so we have a way of tracking progress.

Ideally I'd like to set a date for release, but considering this is open source maybe that's unrealistic.

Finally, while I'd love to release this in a complete, perfect condition, at some point we have to admit the "perfect is the enemy of good" adage is often true. 😅

**Comment by kentcdodds** [comment]
Thanks for bringing this up! I was literally thinking about this just a few hours ago. So I took the existing issues and put some in a Milestone called [`release`](https://github.com/kentcdodds/glamorous-website/milestone/1) (because projects is not working very well and I'm not huge on them either).

Setting a date will be hard, as you said... So we wont do that.

> perfect is the enemy of good

Very true, I've been guilty of wanting to get things perfect in this project. But yeah, I'm ready to get this thing wrapped up and released. Would love to have it done in a week or two, but we'll see how things go. The amount of work is something that could probably be done in a matter of a day or two, but yeah, OSS :smile:

So, anyone can take any of the `release` milestone issues and run with them.

Also, feel free to take any of the other issues, or take something that isn't an issue at all! <3 OSS!

Thanks everyone. Let's get this done!

**Comment by paulmolluzzo** [comment]
👌 thanks @kentcdodds!

**Comment by paulmolluzzo** [comment]
I think we're close! :crossed_fingers:

**Comment by paulmolluzzo** [comment]
![](https://www.viralviralvideos.com/wp-content/uploads/GIF/2014/12/Congratulations-You-Did-It-GIF-2015.gif)
