### ISSUE TITLE
Finish design

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#26]
This looks kinda funny

<img width="473" alt="screen shot 2017-05-31 at 12 32 13 pm" src="https://cloud.githubusercontent.com/assets/1500684/26647668/446531e4-45fd-11e7-9c3d-83116dc0a9c2.png">

**Comment by kentcdodds** [comment]
Also not sure these colors contrast enough to be accessible #23

**Comment by paulmolluzzo** [comment]
Let's just do a white BG then.

**Comment by kentcdodds** [comment]
I wonder if we could make the code blocks syntax highlighted 🤔

**Comment by kentcdodds** [comment]
Or even better, instead of code blocks, most of them could be ReactLive right?

<img width="972" alt="screen shot 2017-05-31 at 12 44 18 pm" src="https://cloud.githubusercontent.com/assets/1500684/26648198/eb02b318-45fe-11e7-8e09-73d278b09454.png">

**Comment by paulmolluzzo** [comment]
There are options in `marked`, and I think we can do highlighting.

We can make them `react-live` but it won't have that codepen-style like you linked. It'll have the preview above it like on the homepage. If we want that style we need to style it differently.

Also, if we do live embeds we're embedding a component in the markdown, so that's something someone will have to get done and _might_ make the docs harder to maintain.

**Comment by bulby97** [comment]
Yeah my bad for the pink background. It's because of the way I needed to implement the "g + pink background" in the main layout. So you need to specify a white background for every main container in a page :/

**Comment by kentcdodds** [comment]
> Yeah my bad for the pink background.

No worries, we're moving fast and breaking things :)

I really like the React Live stuff so yeah, let's make that happen. I wonder if we could do something with https://github.com/threepointone/markdown-in-js

**Comment by paulmolluzzo** [comment]
Put the background color on the pseudo element?

Or make the markdown wrapper have the background color white.

**Comment by paulmolluzzo** [comment]
@kentcdodds https://github.com/threepointone/markdown-in-js/issues/9

**Comment by kentcdodds** [comment]
I feel no shame in basically taking heavy inspiration with regards to design from the styled-components website:

![screen shot 2017-05-31 at 12 57 40 pm](https://cloud.githubusercontent.com/assets/1500684/26648781/d5145f32-4600-11e7-92c3-bdff84559704.png)

I'd like to move nav to the left (I think we've got an issue for that) on desktop and this experience for mobile:

![stuff](https://cloud.githubusercontent.com/assets/1500684/26648834/fec85248-4600-11e7-8999-3eec7d04fb7e.gif)

**Comment by kentcdodds** [comment]
Ah, gotcha with that markdown issue. We'll have to come up with something else then. 🤔  Definitely want to make it easy to translate :)

**Comment by paulmolluzzo** [comment]
I hear you on the translation. This is why I went the way I did for the markdown, but I'm cool with a better solution if we can find one.

As for the nav and links, I agree with @kentcdodds. We can add links to the markdown in the webpack config for `marked`. The nav itself will have to be creative to be dynamic. (Like pull the headings out of the markdown or something).

I'm also still bothered that the markdown isn't SSR. Styled components hard coded their docs instead of .md files, and I'm super tempted to go down that road. We can do way more stuff if each section is a component.

**Comment by kentcdodds** [comment]
I'd be fine putting stuff in non-`.md` files as long as editing the docs is simple enough. Though I'm not sure how crowdin works so that may not be possible. I'm looking into it right now.

**Comment by iamrudra** [comment]
I think using white background in the code block might also work. Do we want to give that a try first?

**Comment by jonmajorc** [comment]
I tried it with a darker blue. Been busy today to keep up with the conversation!
![image](https://cloud.githubusercontent.com/assets/7799266/26650817/436f76d8-4610-11e7-8762-dc187201e12e.png)

**Comment by kentcdodds** [comment]
Cool! Wonder if we can bump the font size 🤔

**Comment by jonmajorc** [comment]
Would it be best to make mobile wireframes for everyone?

**Comment by kentcdodds** [comment]
Yeah, more designs would definitely help 👍

**Comment by jonmajorc** [comment]
On it! I should hopefully have something by tonight with anything from mobile and/or other pages. 👍

**Comment by kentcdodds** [comment]
Awesome!

**Comment by jonmajorc** [comment]
More to come but here are some pics 😃 

Cleaned up the home page. 1) Removed navbar and made it similar to styled-components navigation is handled after you go to the documentation.
![home](https://cloud.githubusercontent.com/assets/7799266/26711801/9e7f5ba6-4728-11e7-9912-acca9b942ae7.png)
Responsive mobile landing page.
![home_mobile](https://cloud.githubusercontent.com/assets/7799266/26711818/b66c8b9e-4728-11e7-888e-003269e64ef6.png)
Documentation page! This page I think I will need help on layout for where to display things from within the README and any other markdown file (CONTRIBUTING, CODE_OF_CONDUCT, and etc.)
![docs](https://cloud.githubusercontent.com/assets/7799266/26711948/8fab46fc-4729-11e7-9d49-60d07a37cabc.png)

**Comment by paulmolluzzo** [comment]
Nice!

@jonmajorc the README and other root-level markdown documents aren't rendered in the site, so we don't need to design for them.

**Comment by jonmajorc** [comment]
Thanks!

By "rendered", do you mean by verbatim the README pasted within the site? Currently [docs](https://glamorous-website-poiyvykcjm.now.sh/docs) is displaying what is inside the README.md.

**Comment by paulmolluzzo** [comment]
You're right, it's taken from the `glamorous` README, but _this_ repo's README isn't on the site. Nor would the other markdown files (CoC, license) be shown. They're just in the repo.

Also, the documentation might not stay 1-to-1 with the `glamorous` README. It'll likely diverge as the documentation improves.

**Comment by kentcdodds** [comment]
Yeah, once this site is done, I'll update the `glamorous` README to be more project-information-type stuff, like [babel's](https://github.com/babel/babel) :)

**Comment by jonmajorc** [comment]
Hey, sorry for the rework... 🙄 I think you all will like it though! (I think...) Download the zip and open each svg up in your browser! Hope you all enjoy! I did some searching around how others out there are doing it besides styled-components and it got my brain jogging. I really like how Jest does their recognition for companies so ya'll will see that same idea within my designs. Anyways, check it out! I also included a design style guide (that is simple). I will try not to change anything now... 🙃
[glamorous_site.zip](https://github.com/kentcdodds/glamorous-website/files/1049267/glamorous_site.zip)

**Comment by kentcdodds** [comment]
Sweet! Here are screenshots of those designs (for folks who don't wanna download it):

![screen shot 2017-06-03 at 7 44 01 am](https://cloud.githubusercontent.com/assets/1500684/26754071/b903777e-4830-11e7-9f1d-bb67f8a2fef8.png)

![screen shot 2017-06-03 at 7 44 22 am](https://cloud.githubusercontent.com/assets/1500684/26754069/b9018e0a-4830-11e7-85e3-c116c4892818.png)

![screen shot 2017-06-03 at 7 44 37 am](https://cloud.githubusercontent.com/assets/1500684/26754070/b9030d5c-4830-11e7-8630-f399b603ad96.png)

![screen shot 2017-06-03 at 7 44 50 am](https://cloud.githubusercontent.com/assets/1500684/26754072/b905fcec-4830-11e7-9b32-525acde94405.png)

![screen shot 2017-06-03 at 7 45 16 am](https://cloud.githubusercontent.com/assets/1500684/26754073/b906562e-4830-11e7-9451-ee6a7fbd9579.png)

We really need to get some of those companies using glamorous ;-)

**Comment by paulmolluzzo** [comment]
Thanks for all this work @jonmajorc! I can see a lot of thought went into it!

I do have a few issues with these new designs I'd like to discuss. I think they're fairly minor:

* We lost the main omnipresent navigation, which is critical to keep. On mobile I think the hidden nav can be more obvious. Say what you will about the hamburger icon, but most people know what it is. 😀
* I'm not crazy about the logos of companies that use `glamorous`. It's inaccurate and clashes with the design. I really liked the original way you listed them as just white text, and would be cool with a single color svg outline of the logos. The full color logos is just too much IMO. (Side note: FPOs should not use logos we don't have permission to use. I don't want to step on anyone's toes. 😉)
* I'm a little lost with the navigation, and with @kentcdodds' recent translation work I think we need to revisit this separately and make a site map to clarify it all. The design of the navigation is cool! Again, on desktop the top level nav should be always visible I think. (There's so much space anyway.)
*The locale selector is super styled, and IME heavily styled `selects` become a11y issues. A CSS wiz might have a solution I don't, but we need to give that some thought especially in light of the implementation we started in #41. These are going to be links to the current page in available languages, so how we want to implement it I'm not 100% sure of.

Overall I think we have a great design here and implemented in the code base.  Really great work @jonmajorc! 🙌🙌

Anyone have thoughts or comments? Anyone want to tackle some of these style updates?

**Comment by jonmajorc** [comment]
Thanks @paulmolluzzo ! Great feedback! 

> We lost the main omnipresent navigation, which is critical to keep. On mobile I think the hidden nav can be more obvious. Say what you will about the hamburger icon, but most people know what it is. 😀

I agree with you on this! I had that originally but I changed it because I had something conflicting in the same area that is no longer there. Hamburger it is! 🍔 

> I'm not crazy about the logos of companies that use glamorous. It's inaccurate and clashes with the design. I really liked the original way you listed them as just white text, and would be cool with a single color svg outline of the logos. The full color logos is just too much IMO. (Side note: FPOs should not use logos we don't have permission to use. I don't want to step on anyone's toes. 😉)

Yeah I figured that be an issue... Babel and Jest does it the way by providing companies' actual logos. I fear the original look with the white text won't look as nice when we scale the amount of companies. i.e: [Babel](https://babeljs.io) and [Jest](https://facebook.github.io/jest/) have at the bottom their home page the users using their tool and you can click to see additional users. I like that idea of potentially seeing more user and the ability to add your company as user through a PR like both Babel and Jest has. Side note, what is FPO?

Navigation we can keep how it was and then we can easily add more navbar items! Yeah, the locale dropdown I am unsure how to handle that as a dropdown; however, having the navbar back we can do it like Jest does!
![image](https://cloud.githubusercontent.com/assets/7799266/26762559/09dcd2ba-490a-11e7-8397-c13975ad3393.png)

Thanks again for the comments! 👍

**Comment by kentcdodds** [comment]
I think we should push the "Used By" stuff to after initial release. We still need to get more companies using/reporting their usage of glamorous :) We can talk about how to do it then.

For language selection, I'm fine with what's in the design already. I really don't care too much actually :)

I'm going to file an issue for search. That'd be great to get. Unsure how to go about that.

**Comment by paulmolluzzo** [comment]
> I fear the original look with the white text won't look as nice when we scale the amount of companies.

Future problem. I think we can do original release with no logos at all.

FPO = For Placement Only

**Comment by kentcdodds** [comment]
> I think we can do original release with no logos at all.

To take it further... I think we can do the initial release with no companies at all 😉

**Comment by paulmolluzzo** [comment]
Yes @kentcdodds, that's what I meant as well. 😀

**Comment by jonmajorc** [comment]
Based on renaming this issue, I can work on Finishing designs if you are all well pleased with what I cooked up earlier. You can also let me know what I should focus on doing 👍. Also, based on the designs I currently built, if there are any examples you want to provide that you would like to see glamorous build from send me them! Let me know when you would like the designs by to 😃

**Comment by kentcdodds** [comment]
I'm pretty happy with what you've got. And we can always iterate! I'm not concerned so much about focus as I am about getting whatever's next done. So work on whatever suits your fancy. It all needs to get done before we can release anyway 🙃  As for when, this is OSS so do it whenever you want. Nobody can ask any more of you than that. Just comment in here when you've started working on something (and mention what you're working on) so we don't work on the same thing at the same time :)

Thanks so much!

**Comment by jonmajorc** [comment]
@kentcdodds what screenshot tool were you using on my designs? 😃

**Comment by kentcdodds** [comment]
Haha, I just pulled them up in Chrome and screenshotted them there ;-)

**Comment by jonmajorc** [comment]
Here are the designs that I have. Give me some feedback and I can the updates if need be. 😃 

# Home Page
<img width="1440" alt="glamorous_home_desktop" src="https://user-images.githubusercontent.com/7799266/27003894-463f36ca-4dc5-11e7-9e8c-78401b2175d8.png">

## Home Page (Mobile)
<img width="375" alt="glamorous_home_mobile" src="https://user-images.githubusercontent.com/7799266/27003899-5dae8a68-4dc5-11e7-9b75-52f368b99d85.png">

## Home Page (Mobile with dropdown)

I am not feeling too ecstatic about the dropdown. The dropdown is pretty plain. I don't have the full resources for the glamorous logos either. I may have been able to do something cool with the dropdown using the resources, but If anyone has any idea of how to tackle the dropdown and locale for now, please speak up!
<img width="375" alt="glamorous_home_mobile_dropdown" src="https://user-images.githubusercontent.com/7799266/27003900-5daf82d8-4dc5-11e7-921a-c03c1d09066c.png">

# Documentation Page Structure
I currently have **2** ideas that fit into the current RC of the website. I basically took the current **basics** page and cleaned it up some more in these examples; the content of the page is FOP 😄, so you can really just ignore that part. I kept it similar so we can get the first iteration of the website out there 😃 

## Doc Structure 1
The design basically adheres to the same RC design out there, but I cleaned it up and added some buttons. The design should help us toward a quick release since its very similar to each RC documentation page (basics, advances examples, and etc.)

_Note: I included the lipstick as an active state for navbar items. Not sure if that is what it was intended for on the RC website today -- but it seem kinda fun_ 😄 
<img width="1440" alt="glamorous_doc_desktop_1" src="https://user-images.githubusercontent.com/7799266/27003962-a5dc6f7a-4dc6-11e7-98f7-3d5205ffec31.png">
<img width="375" alt="glamorous_docs_mobile_1" src="https://user-images.githubusercontent.com/7799266/27003963-a5dcc362-4dc6-11e7-807b-21408ed5e52b.png">
<img width="375" alt="glamorous_docs_mobile_dropdown_1" src="https://user-images.githubusercontent.com/7799266/27003964-a5df7328-4dc6-11e7-8bf7-eacc1d2104e8.png">

## Doc Structure 2
<img width="1440" alt="glamorous_docs_desktop_2" src="https://user-images.githubusercontent.com/7799266/27004021-e0bfbf2e-4dc7-11e7-8f4a-37b3329411a7.png">
<img width="375" alt="glamorous_mobile_doc_2" src="https://user-images.githubusercontent.com/7799266/27004020-e0bacce4-4dc7-11e7-9b85-a948ace353ee.png">
<img width="375" alt="glamorous_mobile_dropdown_doc_2" src="https://user-images.githubusercontent.com/7799266/27004019-e0b977fe-4dc7-11e7-9e92-bd3c4647d8d4.png">

💄💎!

**Comment by kentcdodds** [comment]
This looks super fantastic! One thing I thought of right away is on the docs pages we should probably not have such a huge "Hero" logo etc. at the top. That's just a little much. Could we get a more compressed version?

Thanks!

**Comment by kentcdodds** [comment]
Is there anywhere we could put some tasteful animation? 🤔

**Comment by jonmajorc** [comment]
@kentcdodds oh sure! I agree a 100%. I will see what I can do. Can you give me an idea of how much smaller you are thinking?

**Comment by kentcdodds** [comment]
Whatever looks good 😉 we can definitely iterate 😀
I think it'd be good to see a bit of content above the fold.

**Comment by tdeschryver** [comment]
Would a custom 404 page provide added value? 
(Right now the default `now`s 404 page is being used)

**Comment by kentcdodds** [comment]
Yes, a good 404 would be welcome!

**Comment by tdeschryver** [comment]
I tried implementing the users part, but with the logos that I found it kinda looks strange imo.
Does this need to be worked on? 
(Also if I'm asking too many questions or interfering too much you can always say so :smile: )

![image](https://user-images.githubusercontent.com/28659384/27603736-4a3cc9c6-5b77-11e7-8805-f00a34c2531c.png)

**Comment by kentcdodds** [comment]
Yeah, it does look kinda funny... I think a white background would be better. Also, we need to get official permission to use logos.

I want to do users after our initial release. Let's focus on other stuff :)

**Comment by kentcdodds** [comment]
Closing this issue now. We can open new issues for specific design things we want to do...
